replicaCount: 1

image:
  pullPolicy: IfNotPresent
  repository: mastermindg/argocd-example-app
  tag: 8c9b1f9a14373fcc277be189f06c5b7f7c5131d6

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: example.localdev.me
      paths: []
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

