replicaCount: 1

image:
  pullPolicy: IfNotPresent
  repository: mastermindg/argocd-example-app
  version: c95b3641485ae3d14e3817f822682998a63f3d85

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: example.localdev.me
      paths: []
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

