replicaCount: 1

image:
  pullPolicy: IfNotPresent
  repository: mastermindg/argocd-example-app
  tag: fcbec6ca3a52ff6146f6c55261046dfabfdcd3cc

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: example.localdev.me
      paths: []
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

