replicaCount: 1

image:
  pullPolicy: IfNotPresent
  repository: mastermindg/argocd-example-app
  tag: a4db7287a27820b294dc118b662bfbd598f22d78

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: example.localdev.me
      paths: []
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

